### ISSUE TITLE
GORM Dynamic Finders Checker

### ISSUE THREAD

**Issue by musketyr** [virtualdogbert/enterprise-groovy#3]
Hi @virtualdogbert,

I have created a GORM dynamic finder checker AST transformation for my project and now I'm thinking about how to open-source it. It might be a good addition to Enterprise Groovy WDYT?

**Comment by virtualdogbert** [comment]
Hi @musketyr 
I think it would probably be better as a separate library, or plugin/Micronaut configuration, as Enterprise Groovy doesn't really have anything to do with GORM specifically. Sounds like a good idea though.

**Comment by musketyr** [comment]
ok, @virtualdogbert. Enterprise Groovy is doing a great job with Grails/GORM as you can add only some of the `compileStaticExtensions` to disallow some parts of GORM but sure, I can make it a separate library as originally intended
